name: Checkout repo via SSH
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: ssh-pipeline
      uses: appleboy/ssh-action@master
      env:
        FOO: "BAR"
        BAR: "FOO"
        REPO_URL: "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git"
        FOLDER: "(${GITHUB_REPOSITORY//// })"
        TEST: "${{ env.GITHUB_SERVER_URL }}"
      with:
        # ssh remote host
        host: ${{ secrets.REMOTE_HOST }}
        # ssh remote port
        port: 22 # optional, default is 22
        # ssh remote user
        username: ${{ secrets.REMOTE_USER }}
        # content of ssh private key. ex raw content of ~/.ssh/id_rsa
        key: ${{ secrets.REMOTE_PRIVATE_KEY }} # optional
        envs: REPO_URL, FOO, BAR, $GITHUB_SERVER_URL, $GITHUB_REPOSITORY, FOLDER, TEST
        script: | 
          echo $TEST
          git clone $REPO_URL
          echo $FOLDER
          virtualenv venv 
          source venv/bin/activate
          pip3 install numpy
          pip3 freeze
          ls -ll
        
